// <auto-generated />
using System;
using EF_VishalChavda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF_VishalChavda.Migrations
{
    [DbContext(typeof(EFCont))]
    [Migration("20211212205040_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF_VishalChavda.Models.Product", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Name");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EF_VishalChavda.Models.SaleItem", b =>
                {
                    b.Property<string>("SaleName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SaleName");

                    b.HasIndex("ProductName");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("EF_VishalChavda.Models.SaleItem", b =>
                {
                    b.HasOne("EF_VishalChavda.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductName");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
